export type StudentProperty = {
  id: string;
  title: string;
  description: string;
  images: string[];
  floor_plan_url?: string;
  virtual_tour_url?: string;
  size_sqm: number;
  rooms: number;
  bathrooms: number;
  has_kitchen: boolean;
  has_living_room: boolean;
  has_balcony: boolean;
  is_furnished: boolean;
  appliances: string[];
  utilities: string[];
  internet_available: boolean;
  internet_speed?: number;
  address: string;
  city: string;
  postal_code: string;
  latitude: number;
  longitude: number;
  market_price_monthly: number;
  discounted_price_monthly: number;
  discount_percentage: number;
  deposit_amount: number;
  utilities_included: boolean;
  estimated_utilities_cost?: number;
  availability_start: string;
  availability_end: string;
  academic_year: string;
  current_status: 'available' | 'reserved' | 'occupied' | 'maintenance';
};

export type SearchFilters = {
  city?: string;
  university?: string;
  minPrice?: number;
  maxPrice?: number;
  rooms?: number;
  furnished?: boolean;
};
